export const instances = [
    {
        name: 'yellow-white rings',
        _id: 'kj434dkjfjf',
        createdAt: '2024-05-26T13:48:06.590Z',
        instanceName: 'Rose Ring',
    },
];

export const instanceData = [
    {
        name: 'yellow-white rings',
        _id: 'kj434dkjfjf',
        createdAt: '2024-05-26T13:48:06.590Z',
        instanceName: 'Rose Ring',
        data: [
            {
                _id: "product1",
                productName: "WEB2400001",
                value: "DW-ct / GW-5.22gms",
                goldWt: "5.93",
                ct: "18",
                metal: "14K",
                metalWt: "5.2184",
                image: "w-ROR2400001.jpg",
                metalColor: "white",
            },
            {
                _id: "product2",
                productName: "WEB2400002",
                value: "DW-0.6ct / GW-4.39gms",
                goldWt: "4.99",
                ct: "18",
                diamondWeight: "0.6",
                metal: "14K",
                metalWt: "4.3912",
                image: "w-ROR2400001b.jpg",
                metalColor: "white",
            },
            {
                _id: "product3",
                productName: "WEB2400003",
                value: "DW-0.25ct / GW-3.10gms",
                goldWt: "3.52",
                ct: "18",
                diamondWeight: "0.25",
                metal: "14K",
                metalWt: "3.0976",
                image: "w-ROR2400001c.jpg",
                metalColor: "white",
            },
            {
                _id: "product4",
                productName: "WEB2400001",
                value: "DW-ct / GW-5.22gms",
                goldWt: "5.93",
                ct: "18",
                metal: "14K",
                metalWt: "5.2184",
                image: "w-ROR2400001.jpg",
                metalColor: "white",
            },
            {
                _id: "product5",
                productName: "WEB2400002",
                value: "DW-0.6ct / GW-4.39gms",
                goldWt: "4.99",
                ct: "18",
                diamondWeight: "0.6",
                metal: "14K",
                metalWt: "4.3912",
                image: "w-ROR2400001b.jpg",
                metalColor: "white",
            },
            {
                _id: "product6",
                productName: "WEB2400003",
                value: "DW-0.25ct / GW-3.10gms",
                goldWt: "3.52",
                ct: "18",
                diamondWeight: "0.25",
                metal: "14K",
                metalWt: "3.0976",
                image: "w-ROR2400001c.jpg",
                metalColor: "white",
            },
            {
                _id: "product7",
                productName: "WEB2400001",
                value: "DW-ct / GW-5.22gms",
                goldWt: "5.93",
                ct: "18",
                metal: "14K",
                metalWt: "5.2184",
                image: "w-ROR2400001.jpg",
                metalColor: "white",
            },
            {
                _id: "product8",
                productName: "WEB2400002",
                value: "DW-0.6ct / GW-4.39gms",
                goldWt: "4.99",
                ct: "18",
                diamondWeight: "0.6",
                metal: "14K",
                metalWt: "4.3912",
                image: "w-ROR2400001b.jpg",
                metalColor: "white",
            },
            {
                _id: "product9",
                productName: "WEB2400003",
                value: "DW-0.25ct / GW-3.10gms",
                goldWt: "3.52",
                ct: "18",
                diamondWeight: "0.25",
                metal: "14K",
                metalWt: "3.0976",
                image: "w-ROR2400001c.jpg",
                metalColor: "white",
            },
            {
                _id: "product10",
                productName: "WEB2400001",
                value: "DW-ct / GW-5.22gms",
                goldWt: "5.93",
                ct: "18",
                metal: "14K",
                metalWt: "5.2184",
                image: "w-ROR2400001.jpg",
                metalColor: "white",
            },
            {
                _id: "product11",
                productName: "WEB2400002",
                value: "DW-0.6ct / GW-4.39gms",
                goldWt: "4.99",
                ct: "18",
                diamondWeight: "0.6",
                metal: "14K",
                metalWt: "4.3912",
                image: "w-ROR2400001b.jpg",
                metalColor: "white",
            },
            {
                _id: "product12",
                productName: "WEB2400003",
                value: "DW-0.25ct / GW-3.10gms",
                goldWt: "3.52",
                ct: "18",
                diamondWeight: "0.25",
                metal: "14K",
                metalWt: "3.0976",
                image: "w-ROR2400001c.jpg",
                metalColor: "white",
            },
            {
                _id: "product13",
                productName: "WEB2400001",
                value: "DW-ct / GW-5.22gms",
                goldWt: "5.93",
                ct: "18",
                metal: "14K",
                metalWt: "5.2184",
                image: "w-ROR2400001.jpg",
                metalColor: "white",
            },
            {
                _id: "product14",
                productName: "WEB2400002",
                value: "DW-0.6ct / GW-4.39gms",
                goldWt: "4.99",
                ct: "18",
                diamondWeight: "0.6",
                metal: "14K",
                metalWt: "4.3912",
                image: "w-ROR2400001b.jpg",
                metalColor: "white",
            },
            {
                _id: "product15",
                productName: "WEB2400003",
                value: "DW-0.25ct / GW-3.10gms",
                goldWt: "3.52",
                ct: "18",
                diamondWeight: "0.25",
                metal: "14K",
                metalWt: "3.0976",
                image: "w-ROR2400001c.jpg",
                metalColor: "white",
            },
        ]
    },
    {
        name: 'yellow-white rings type 2',
        _id: '667267362dfDF',
        createdAt: '2024-05-26T13:48:06.590Z',
        instanceName: 'Rose Ring',
        data: [
            {
                _id: "product1",
                productName: "WEB2400001",
                value: "DW-ct / GW-5.22gms",
                goldWt: "5.93",
                ct: "18",
                metal: "14K",
                metalWt: "5.2184",
                image: "w-ROR2400001.jpg",
                metalColor: "white",
            },
            {
                _id: "product2",
                productName: "WEB2400002",
                value: "DW-0.6ct / GW-4.39gms",
                goldWt: "4.99",
                ct: "18",
                diamondWeight: "0.6",
                metal: "14K",
                metalWt: "4.3912",
                image: "w-ROR2400001b.jpg",
                metalColor: "white",
            },
            {
                _id: "product3",
                productName: "WEB2400003",
                value: "DW-0.25ct / GW-3.10gms",
                goldWt: "3.52",
                ct: "18",
                diamondWeight: "0.25",
                metal: "14K",
                metalWt: "3.0976",
                image: "w-ROR2400001c.jpg",
                metalColor: "white",
            },
            {
                _id: "product4",
                productName: "WEB2400001",
                value: "DW-ct / GW-5.22gms",
                goldWt: "5.93",
                ct: "18",
                metal: "14K",
                metalWt: "5.2184",
                image: "w-ROR2400001.jpg",
                metalColor: "white",
            },
            {
                _id: "product5",
                productName: "WEB2400002",
                value: "DW-0.6ct / GW-4.39gms",
                goldWt: "4.99",
                ct: "18",
                diamondWeight: "0.6",
                metal: "14K",
                metalWt: "4.3912",
                image: "w-ROR2400001b.jpg",
                metalColor: "white",
            },
            {
                _id: "product6",
                productName: "WEB2400003",
                value: "DW-0.25ct / GW-3.10gms",
                goldWt: "3.52",
                ct: "18",
                diamondWeight: "0.25",
                metal: "14K",
                metalWt: "3.0976",
                image: "w-ROR2400001c.jpg",
                metalColor: "white",
            },
            {
                _id: "product7",
                productName: "WEB2400001",
                value: "DW-ct / GW-5.22gms",
                goldWt: "5.93",
                ct: "18",
                metal: "14K",
                metalWt: "5.2184",
                image: "w-ROR2400001.jpg",
                metalColor: "white",
            },
            {
                _id: "product8",
                productName: "WEB2400002",
                value: "DW-0.6ct / GW-4.39gms",
                goldWt: "4.99",
                ct: "18",
                diamondWeight: "0.6",
                metal: "14K",
                metalWt: "4.3912",
                image: "w-ROR2400001b.jpg",
                metalColor: "white",
            },
            {
                _id: "product9",
                productName: "WEB2400003",
                value: "DW-0.25ct / GW-3.10gms",
                goldWt: "3.52",
                ct: "18",
                diamondWeight: "0.25",
                metal: "14K",
                metalWt: "3.0976",
                image: "w-ROR2400001c.jpg",
                metalColor: "white",
            },
            {
                _id: "product10",
                productName: "WEB2400001",
                value: "DW-ct / GW-5.22gms",
                goldWt: "5.93",
                ct: "18",
                metal: "14K",
                metalWt: "5.2184",
                image: "w-ROR2400001.jpg",
                metalColor: "white",
            },
            {
                _id: "product11",
                productName: "WEB2400002",
                value: "DW-0.6ct / GW-4.39gms",
                goldWt: "4.99",
                ct: "18",
                diamondWeight: "0.6",
                metal: "14K",
                metalWt: "4.3912",
                image: "w-ROR2400001b.jpg",
                metalColor: "white",
            },
            {
                _id: "product12",
                productName: "WEB2400003",
                value: "DW-0.25ct / GW-3.10gms",
                goldWt: "3.52",
                ct: "18",
                diamondWeight: "0.25",
                metal: "14K",
                metalWt: "3.0976",
                image: "w-ROR2400001c.jpg",
                metalColor: "white",
            },
            {
                _id: "product13",
                productName: "WEB2400001",
                value: "DW-ct / GW-5.22gms",
                goldWt: "5.93",
                ct: "18",
                metal: "14K",
                metalWt: "5.2184",
                image: "w-ROR2400001.jpg",
                metalColor: "white",
            },
            {
                _id: "product14",
                productName: "WEB2400002",
                value: "DW-0.6ct / GW-4.39gms",
                goldWt: "4.99",
                ct: "18",
                diamondWeight: "0.6",
                metal: "14K",
                metalWt: "4.3912",
                image: "w-ROR2400001b.jpg",
                metalColor: "white",
            },
            {
                _id: "product15",
                productName: "WEB2400003",
                value: "DW-0.25ct / GW-3.10gms",
                goldWt: "3.52",
                ct: "18",
                diamondWeight: "0.25",
                metal: "14K",
                metalWt: "3.0976",
                image: "w-ROR2400001c.jpg",
                metalColor: "white",
            },
            {
                _id: "product16",
                productName: "WEB2400001",
                value: "DW-ct / GW-5.22gms",
                goldWt: "5.93",
                ct: "18",
                metal: "14K",
                metalWt: "5.2184",
                image: "y-ROR2400001.jpg",
                metalColor: "yellow",
            },
            {
                _id: "product17",
                productName: "WEB2400002",
                value: "DW-0.6ct / GW-4.39gms",
                goldWt: "4.99",
                ct: "18",
                diamondWeight: "0.6",
                metal: "14K",
                metalWt: "4.3912",
                image: "y-ROR2400001b.jpg",
                metalColor: "yellow",
            },
            {
                _id: "product18",
                productName: "WEB2400003",
                value: "DW-0.25ct / GW-3.10gms",
                goldWt: "3.52",
                ct: "18",
                diamondWeight: "0.25",
                metal: "14K",
                metalWt: "3.0976",
                image: "y-ROR2400001c.jpg",
                metalColor: "yellow",
            },
            {
                _id: "product19",
                productName: "WEB2400001",
                value: "DW-ct / GW-5.22gms",
                goldWt: "5.93",
                ct: "18",
                metal: "14K",
                metalWt: "5.2184",
                image: "y-ROR2400001.jpg",
                metalColor: "yellow",
            },
            {
                _id: "product20",
                productName: "WEB2400002",
                value: "DW-0.6ct / GW-4.39gms",
                goldWt: "4.99",
                ct: "18",
                diamondWeight: "0.6",
                metal: "14K",
                metalWt: "4.3912",
                image: "y-ROR2400001b.jpg",
                metalColor: "yellow",
            },
            {
                _id: "product21",
                productName: "WEB2400003",
                value: "DW-0.25ct / GW-3.10gms",
                goldWt: "3.52",
                ct: "18",
                diamondWeight: "0.25",
                metal: "14K",
                metalWt: "3.0976",
                image: "y-ROR2400001c.jpg",
                metalColor: "yellow",
            },
            {
                _id: "product22",
                productName: "WEB2400001",
                value: "DW-ct / GW-5.22gms",
                goldWt: "5.93",
                ct: "18",
                metal: "14K",
                metalWt: "5.2184",
                image: "y-ROR2400001.jpg",
                metalColor: "yellow",
            },
            {
                _id: "product23",
                productName: "WEB2400002",
                value: "DW-0.6ct / GW-4.39gms",
                goldWt: "4.99",
                ct: "18",
                diamondWeight: "0.6",
                metal: "14K",
                metalWt: "4.3912",
                image: "y-ROR2400001b.jpg",
                metalColor: "yellow",
            },
            {
                _id: "product24",
                productName: "WEB2400003",
                value: "DW-0.25ct / GW-3.10gms",
                goldWt: "3.52",
                ct: "18",
                diamondWeight: "0.25",
                metal: "14K",
                metalWt: "3.0976",
                image: "y-ROR2400001c.jpg",
                metalColor: "yellow",
            },
            {
                _id: "product25",
                productName: "WEB2400002",
                value: "DW-0.6ct / GW-4.39gms",
                goldWt: "4.99",
                ct: "18",
                diamondWeight: "0.6",
                metal: "14K",
                metalWt: "4.3912",
                image: "w-ROR2400001b.jpg",
                metalColor: "white",
            },
        ]
    },
];